### ISSUE TITLE
Group wise permissioning for users

### ISSUE THREAD

**Issue by aktech** [Quansight/qhub-ops#73]
Currently there is no way to create different set of permissions for each user or group

Although there are ways outside QHub, people can create service accounts for each user or group and use then for daily tasks. It would be great to have this functionality in the QHub itself.

A solution would be to create a section in config.yml somewhere close to the users that defines cloud IAM permissions for a particular user. So when you render the project, it will create service account for each user/group and push that service account file in the mounted NFS for respective users, so that they have correct permissions.

**Comment by costrouc** [comment]
@aktech and I spoke about the importance of keeping the `qhub-ops-config.yaml` as the central source of truth for reproducibility. We ended up having a talk about a general way to support adding secrest to users. This is very much up for change but something like this is along the idea of what is going to be implemented.

We would leverage terraform to auto generate the gcp/aws credentials they may need. These secrets will then be mounted with the nfs server into the users home directory or in the shared group directoires.

```
security:
  users:
    costrouc:
      uid: 10000
      primary_group: users
      secrets:
        - name: gcp_credentials
          type: gcp
          permissions:
            - read
            - write
        - name: mysecret1
          type: b64secret
          value: "ASDFASDFQWEFAFASVASDFQWER"
        - name: mysecret2
          type: secret
          secret_name: "apitoken"

  groups:
    users:
      gid: 20000
      secrets:
        - name: gcp_credentials
          type: gcp
          permissions:
            - read
            - write
        - name: mysecret
          type: secret
          value: "base64 encoded secret"
```
