### ISSUE TITLE
Ability to add secrets available to specific users and or groups

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub-ops#75]
@aktech and I spoke about the importance of keeping the `qhub-ops-config.yaml` as the central source of truth for reproducibility. We ended up having a talk about a general way to support adding secrest to users. This is very much up for change but something like this is along the idea of what is going to be implemented.

We would leverage terraform to auto generate the gcp/aws credentials they may need. These secrets will then be mounted with the nfs server into the users home directory or in the shared group directoires.

```
security:
  users:
    costrouc:
      uid: 10000
      primary_group: users
      secrets:
        - name: gcp_credentials
          type: gcp
          permissions:
            - read
            - write
        - name: mysecret1
          type: b64secret
          value: "ASDFASDFQWEFAFASVASDFQWER"
        - name: mysecret2
          type: secret
          secret_name: "apitoken"

  groups:
    users:
      gid: 20000
      secrets:
        - name: gcp_credentials
          type: gcp
          permissions:
            - read
            - write
        - name: mysecret
          type: secret
          value: "base64 encoded secret"
```
